name: Test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11
      - run: sudo apt-get install emscripten
      - run: npm install
      - run: make
      - run: find wasm
      - run: npm test
